export interface LegacyTemplate {
  id: string;
  name: string;
  documentType: string;
  category: string;
  troSensitive: boolean;
  emergencyEligible: boolean;
  recorderRequired: boolean;
  defaultDoctrines: string[];
  defaultFederalStatutes: string[];
  signatureRequirements: string[];
  buildContent: (vars: Record<string, string>) => string;
  buildSignatureBlock: (vars: Record<string, string>) => string;
}

function sig(vars: Record<string, string>, role = "Chief Justice & Trustee"): string {
  return [
    `SOVEREIGN OFFICE OF THE CHIEF JUSTICE & TRUSTEE`,
    ``,
    `_________________________________      Date: ________________`,
    `${vars.officerName ?? role}`,
    `${vars.officerTitle ?? role}`,
    `Sovereign Office of the Chief Justice & Trustee`,
    ``,
    `_________________________________      Date: ________________`,
    `Intake Officer / Authorized Representative`,
    `Badge/ID: _______________________`,
  ].join("\n");
}

export const LEGACY_TEMPLATES: LegacyTemplate[] = [
  {
    id: "TRO_ICWA",
    name: "TRO — ICWA Child Welfare",
    documentType: "tro",
    category: "ICWA",
    troSensitive: true,
    emergencyEligible: true,
    recorderRequired: false,
    defaultDoctrines: [
      "Indian Child Welfare Act, 25 U.S.C. §§ 1901–1963",
      "Mississippi Band of Choctaw Indians v. Holyfield, 490 U.S. 30 (1989)",
      "Brackeen v. Haaland, 599 U.S. 255 (2023)",
      "Indian Canons of Construction — Montana v. Blackfeet Tribe, 471 U.S. 759 (1985)",
      "Federal Trust Responsibility",
    ],
    defaultFederalStatutes: [
      "25 U.S.C. § 1911 — Exclusive tribal court jurisdiction",
      "25 U.S.C. § 1912 — Notice and intervention requirements",
      "25 U.S.C. § 1912(d) — Active efforts requirement",
      "25 U.S.C. § 1912(e) — Expert witness requirement",
      "25 U.S.C. § 1915 — Placement preferences",
      "25 U.S.C. § 1920 — Return of custody",
    ],
    signatureRequirements: ["Chief Justice & Trustee", "Intake Officer"],
    buildContent(vars) {
      return [
        `IN THE SOVEREIGN COURT OF THE CHIEF JUSTICE & TRUSTEE`,
        `TRIBAL COURT — ICWA DIVISION`,
        ``,
        `Case No.: ${vars.caseNumber ?? "___________"}`,
        `Court: ${vars.court ?? "Tribal Court"}`,
        ``,
        `IN RE THE MATTER OF: ${vars.childName ?? "[CHILD NAME]"}, an Indian Child`,
        ``,
        `TEMPORARY RESTRAINING ORDER`,
        `INDIAN CHILD WELFARE ACT — 25 U.S.C. §§ 1901–1963`,
        ``,
        `FINDINGS OF FACT`,
        ``,
        `1. INDIAN CHILD STATUS: ${vars.childName ?? "The subject child"} is an Indian child as defined by the Indian Child Welfare Act, 25 U.S.C. § 1903(4), being a member of, or eligible for membership in, ${vars.tribe ?? "a federally recognized Indian tribe"}.`,
        ``,
        `2. TRIBAL JURISDICTION: Pursuant to 25 U.S.C. § 1911, this Court has ${vars.jurisdictionType ?? "exclusive/concurrent"} jurisdiction over this matter. Any state court proceedings affecting this Indian child are subject to mandatory transfer to this Tribal Court upon motion.`,
        ``,
        `3. IMMINENT HARM: The Court finds that ${vars.harmDescription ?? "immediate action is necessary to prevent imminent harm to the Indian child"}. Delay in issuance of this Order would cause irreparable harm.`,
        ``,
        `4. ACTIVE EFFORTS: The Sovereign Office has made active efforts as required by 25 U.S.C. § 1912(d) to prevent the breakup of the Indian family. Those efforts have been unsuccessful due to: ${vars.effortDescription ?? "[state circumstances]"}.`,
        ``,
        `5. ICWA NOTICE: Notice has been or is being provided to ${vars.tribe ?? "the relevant tribe(s)"} and the Bureau of Indian Affairs as required by 25 U.S.C. § 1912(a).`,
        ``,
        `ORDER`,
        ``,
        `IT IS HEREBY ORDERED that:`,
        ``,
        `1. RESTRAINING ORDER: ${vars.respondent ?? "All state and county agencies"} are immediately RESTRAINED from: (a) removing ${vars.childName ?? "the Indian child"} from tribal/family custody; (b) proceeding with any state court child custody proceeding without ICWA compliance; (c) placing the child in any placement inconsistent with 25 U.S.C. § 1915.`,
        ``,
        `2. ICWA COMPLIANCE: All proceedings must comply with the full requirements of ICWA. Expert witness testimony as required by 25 U.S.C. § 1912(e) must be obtained before any state placement order issues.`,
        ``,
        `3. TRANSFER TO TRIBAL COURT: Pursuant to 25 U.S.C. § 1911(b), this matter is transferred to the jurisdiction of this Tribal Court. Any pending state court proceedings are stayed pending full ICWA compliance.`,
        ``,
        `4. IMMEDIATE EFFECT: This Order is effective immediately upon issuance and shall remain in force until further order of this Court or until a full hearing is held on ${vars.hearingDate ?? "a date to be set by the Court"}.`,
        ``,
        `5. HEARING: A full hearing on this matter is scheduled for: ${vars.hearingDate ?? "___________"} at ${vars.hearingTime ?? "___________"}.`,
        ``,
        `FEDERAL LAW AUTHORITY`,
        ``,
        `This Order is issued under the authority of the Indian Child Welfare Act of 1978, 25 U.S.C. §§ 1901–1963; the inherent sovereign authority of the tribal court; and the Federal Trust Responsibility of the United States to Indian tribes and their members. Pursuant to Worcester v. Georgia, 31 U.S. 515 (1832), this Order supersedes any contrary state court order.`,
        ``,
        `Issued at: ${vars.issuedAt ?? "Sovereign Office of the Chief Justice & Trustee"}`,
        `Date: ${vars.issuedDate ?? new Date().toLocaleDateString()}`,
        `Time: ${vars.issuedTime ?? new Date().toLocaleTimeString()}`,
      ].join("\n");
    },
    buildSignatureBlock: sig,
  },

  {
    id: "TRO_GENERAL",
    name: "TRO — General Tribal Jurisdiction",
    documentType: "tro",
    category: "General",
    troSensitive: true,
    emergencyEligible: true,
    recorderRequired: false,
    defaultDoctrines: [
      "Worcester v. Georgia, 31 U.S. 515 (1832)",
      "White Mountain Apache Tribe v. Bracker, 448 U.S. 136 (1980)",
      "Federal Trust Responsibility",
      "Tribal Sovereign Authority",
    ],
    defaultFederalStatutes: [
      "25 U.S.C. § 13 — Snyder Act (federal welfare authority)",
      "18 U.S.C. § 2265 — Full faith and credit for tribal protection orders",
      "25 U.S.C. § 1304 — VAWA tribal provisions",
    ],
    signatureRequirements: ["Chief Justice & Trustee", "Intake Officer"],
    buildContent(vars) {
      return [
        `IN THE SOVEREIGN COURT OF THE CHIEF JUSTICE & TRUSTEE`,
        ``,
        `Case No.: ${vars.caseNumber ?? "___________"}`,
        ``,
        `TEMPORARY RESTRAINING ORDER`,
        `TRIBAL COURT — SOVEREIGN AUTHORITY`,
        ``,
        `PARTIES:`,
        `Petitioner: ${vars.petitioner ?? "[Petitioner Name]"}`,
        `Respondent: ${vars.respondent ?? "[Respondent Name / Agency]"}`,
        ``,
        `THE COURT FINDS:`,
        ``,
        `1. This Court has jurisdiction over this matter under the inherent sovereign authority of the tribal nation and pursuant to applicable tribal law and federal Indian law.`,
        ``,
        `2. Immediate and irreparable harm will result to ${vars.petitioner ?? "the Petitioner/Indian community"} unless this Order issues immediately.`,
        ``,
        `3. The actions described herein constitute a violation of: ${vars.violationDescription ?? "[describe violations]"}.`,
        ``,
        `4. Federal Indian law preempts any state or local law that conflicts with the rights protected by this Order. McClanahan v. Arizona State Tax Comm'n, 411 U.S. 164 (1973).`,
        ``,
        `ORDER`,
        ``,
        `IT IS HEREBY ORDERED that ${vars.respondent ?? "Respondent(s)"} are immediately RESTRAINED and ENJOINED from:`,
        ``,
        `${vars.restrainedActions ?? "1. [Specify restrained actions]"}`,
        ``,
        `This Order is effective immediately. Violation of this Order may be punishable as contempt of the Sovereign Court.`,
        ``,
        `HEARING DATE: ${vars.hearingDate ?? "___________"}`,
        ``,
        `This Order shall remain in effect until the hearing date or until further order of this Court.`,
        ``,
        `FEDERAL AUTHORITY: This Order is issued under the inherent sovereign authority of this Tribal Court. All persons, agencies, and entities subject to this Order must comply pursuant to the Federal Trust Responsibility and the primacy of federal Indian law. Full faith and credit is required under 18 U.S.C. § 2265.`,
        ``,
        `Issued: ${vars.issuedDate ?? new Date().toLocaleDateString()}`,
      ].join("\n");
    },
    buildSignatureBlock: sig,
  },

  {
    id: "ICWA_NOTICE",
    name: "ICWA Notice of Proceeding",
    documentType: "icwa_notice",
    category: "ICWA",
    troSensitive: true,
    emergencyEligible: false,
    recorderRequired: false,
    defaultDoctrines: [
      "Indian Child Welfare Act, 25 U.S.C. §§ 1901–1963",
      "Brackeen v. Haaland, 599 U.S. 255 (2023)",
      "Mississippi Band of Choctaw Indians v. Holyfield, 490 U.S. 30 (1989)",
    ],
    defaultFederalStatutes: [
      "25 U.S.C. § 1912(a) — Mandatory notice requirements",
      "25 U.S.C. § 1911 — Tribal court jurisdiction",
      "25 U.S.C. § 1911(c) — Right to intervene",
      "25 C.F.R. Part 23 — ICWA regulations",
    ],
    signatureRequirements: ["Chief Justice & Trustee"],
    buildContent(vars) {
      return [
        `NOTICE OF INDIAN CHILD WELFARE ACT PROCEEDING`,
        `25 U.S.C. § 1912(a)`,
        ``,
        `TO: ${vars.noticeTo ?? "Bureau of Indian Affairs / Relevant Tribe(s)"}`,
        `FROM: Sovereign Office of the Chief Justice & Trustee`,
        `RE: ${vars.childName ?? "[Child Name]"}, DOB: ${vars.childDob ?? "Unknown"}`,
        ``,
        `NOTICE IS HEREBY GIVEN that a child custody proceeding has been initiated or is pending in:`,
        `Court: ${vars.court ?? "[Court Name]"}`,
        `Case Number: ${vars.caseNumber ?? "[Case Number]"}`,
        ``,
        `INDIAN CHILD INFORMATION:`,
        `Child's Name: ${vars.childName ?? "[Child Name]"}`,
        `Date of Birth: ${vars.childDob ?? "Unknown"}`,
        `Tribal Affiliation: ${vars.tribe ?? "[Tribe Name]"}`,
        ``,
        `MANDATORY NOTICE REQUIREMENTS:`,
        `Pursuant to 25 U.S.C. § 1912(a), this notice is provided because the above-named child is or may be an Indian child as defined by ICWA (25 U.S.C. § 1903(4)).`,
        ``,
        `RIGHTS AND REQUIRED ACTIONS:`,
        `1. The tribe has an absolute right to intervene in this proceeding under 25 U.S.C. § 1911(c).`,
        `2. The tribe may petition to transfer this proceeding to tribal court under 25 U.S.C. § 1911(b).`,
        `3. A mandatory stay of proceedings applies until ICWA compliance is complete.`,
        `4. Active efforts to prevent family breakup must be demonstrated (25 U.S.C. § 1912(d)).`,
        `5. Placement preferences under 25 U.S.C. § 1915 apply to any out-of-home placement.`,
        ``,
        `RESPONSE REQUIRED: Please respond within 20 days to confirm tribal enrollment status of the above-named child.`,
        ``,
        `Contact: ${vars.contactInfo ?? "Sovereign Office of the Chief Justice & Trustee"}`,
        ``,
        `This notice is issued pursuant to the mandatory requirements of the Indian Child Welfare Act and 25 C.F.R. Part 23.`,
        ``,
        `Date of Notice: ${vars.issuedDate ?? new Date().toLocaleDateString()}`,
      ].join("\n");
    },
    buildSignatureBlock: sig,
  },

  {
    id: "PROTECTIVE_ORDER",
    name: "Tribal Protective Order",
    documentType: "protective_order",
    category: "Protection",
    troSensitive: false,
    emergencyEligible: true,
    recorderRequired: false,
    defaultDoctrines: [
      "Tribal Sovereign Authority",
      "Worcester v. Georgia, 31 U.S. 515 (1832)",
      "VAWA Full Faith and Credit, 18 U.S.C. § 2265",
    ],
    defaultFederalStatutes: [
      "18 U.S.C. § 2265 — Full faith and credit for tribal protection orders",
      "25 U.S.C. § 1304 — VAWA tribal criminal jurisdiction",
      "25 U.S.C. § 13 — Snyder Act welfare authority",
    ],
    signatureRequirements: ["Chief Justice & Trustee", "Intake Officer"],
    buildContent(vars) {
      return [
        `TRIBAL PROTECTIVE ORDER`,
        `SOVEREIGN COURT OF THE CHIEF JUSTICE & TRUSTEE`,
        ``,
        `Order No.: ${vars.caseNumber ?? "PO-" + Date.now()}`,
        ``,
        `Protected Person: ${vars.petitioner ?? "[Protected Person Name]"}`,
        `Respondent: ${vars.respondent ?? "[Respondent Name]"}`,
        ``,
        `FINDINGS:`,
        `1. The Court finds that the Protected Person requires immediate protection from the Respondent.`,
        `2. The Respondent's actions constitute: ${vars.violationDescription ?? "[describe actions]"}.`,
        `3. This Court has jurisdiction under tribal law and federal Indian law.`,
        ``,
        `PROTECTIVE ORDER:`,
        `The Respondent, ${vars.respondent ?? "[Respondent]"}, is hereby ORDERED to:`,
        ``,
        `1. STAY AWAY: Maintain a distance of at least ${vars.stayAwayDistance ?? "100 yards"} from the Protected Person, their home, workplace, vehicle, and any other location frequented by the Protected Person.`,
        ``,
        `2. NO CONTACT: Have no contact, direct or indirect, with the Protected Person, including but not limited to in-person contact, phone calls, text messages, emails, social media, or contact through third parties.`,
        ``,
        `3. VACATE: If applicable, immediately vacate the shared residence at: ${vars.residence ?? "[Shared Residence Address]"}.`,
        ``,
        `4. SURRENDER: Surrender any firearms, weapons, or dangerous instruments to: ${vars.surrenderLocation ?? "the Tribal Court Clerk within 24 hours"}.`,
        ``,
        `FULL FAITH AND CREDIT:`,
        `This Order must be enforced by all state and federal courts and law enforcement agencies pursuant to 18 U.S.C. § 2265. No registration of this Order is required for enforcement. This Order is enforceable in all jurisdictions of the United States.`,
        ``,
        `This Order is effective: ${vars.effectiveDate ?? new Date().toLocaleDateString()}`,
        `This Order expires: ${vars.expirationDate ?? "[Expiration Date]"} unless extended by the Court.`,
        ``,
        `Violation of this Order may be prosecuted as a criminal offense under tribal law and federal law (18 U.S.C. § 2262).`,
      ].join("\n");
    },
    buildSignatureBlock: sig,
  },

  {
    id: "TRUST_DEED",
    name: "Trust Deed Declaration",
    documentType: "trust_deed",
    category: "Trust Land",
    troSensitive: false,
    emergencyEligible: false,
    recorderRequired: true,
    defaultDoctrines: [
      "Federal Trust Responsibility — United States v. Mitchell, 463 U.S. 206 (1983)",
      "Nonintercourse Act — 25 U.S.C. § 177",
      "Indian Reorganization Act — 25 U.S.C. § 5108",
      "Worcester v. Georgia (state law preemption)",
    ],
    defaultFederalStatutes: [
      "25 U.S.C. § 5108 — Indian Reorganization Act — trust land acquisition",
      "25 U.S.C. § 177 — Nonintercourse Act — protection against unauthorized alienation",
      "25 U.S.C. § 2201 — Indian Land Consolidation Act",
      "25 C.F.R. Part 152 — Land acquisition regulations",
    ],
    signatureRequirements: ["Chief Justice & Trustee", "Notary"],
    buildContent(vars) {
      return [
        `DECLARATION OF TRUST STATUS`,
        `NOTICE AFFECTING REAL PROPERTY`,
        ``,
        `THIS DECLARATION is made by the Sovereign Office of the Chief Justice & Trustee, acting under the authority of the United States Federal Trust Responsibility and tribal sovereign authority.`,
        ``,
        `PROPERTY DESCRIPTION:`,
        `${vars.legalDescription ?? "[Legal Description of Land]"}`,
        `APN: ${vars.apn ?? "[APN]"}`,
        `County: ${vars.county ?? "[County]"}`,
        `State: ${vars.state ?? "[State]"}`,
        ``,
        `TRUST STATUS DECLARATION:`,
        `The above-described land is held in trust by the United States Government for the benefit of ${vars.beneficiary ?? "[Tribe / Individual Indian]"} pursuant to the Indian Reorganization Act, 25 U.S.C. § 5108, and/or has been determined to be trust land, allotment land, or restricted Indian land subject to federal protection.`,
        ``,
        `RESTRICTIONS ON ALIENATION:`,
        `This land may not be sold, transferred, leased, mortgaged, or otherwise encumbered without the approval of the Secretary of the Interior or authorized delegate pursuant to 25 U.S.C. § 177 and 25 C.F.R. Part 152. Any purported transfer without such approval is void ab initio.`,
        ``,
        `STATE TAX EXEMPTION:`,
        `This trust land is exempt from state and local taxation pursuant to the Federal Trust Responsibility and McClanahan v. Arizona State Tax Comm'n, 411 U.S. 164 (1973). No state or county tax lien may attach to this property.`,
        ``,
        `FEDERAL PREEMPTION:`,
        `Federal law exclusively governs this trust land. State and county zoning ordinances, building codes, and land use regulations do not apply within Indian Country. Worcester v. Georgia, 31 U.S. 515 (1832).`,
        ``,
        `TRIBAL JURISDICTION:`,
        `The Sovereign Court of the Chief Justice & Trustee retains exclusive jurisdiction over all matters arising from this trust land, including disputes, encroachments, and unlawful claims.`,
        ``,
        `RECORDER NOTICE:`,
        `This instrument is to be recorded in the chain of title. All subsequent purchasers, lenders, and encumbrancers take subject to the trust status and restrictions on alienation described herein. Notice of trust status is constructive notice to all persons.`,
        ``,
        `Executed: ${vars.issuedDate ?? new Date().toLocaleDateString()}`,
        `Reference: ${vars.referenceNumber ?? "[Reference Number]"}`,
      ].join("\n");
    },
    buildSignatureBlock: sig,
  },

  {
    id: "JURISDICTIONAL_STATEMENT",
    name: "Jurisdictional Statement (Federal Supremacy)",
    documentType: "jurisdictional_statement",
    category: "Jurisdiction",
    troSensitive: false,
    emergencyEligible: false,
    recorderRequired: false,
    defaultDoctrines: [
      "Worcester v. Georgia, 31 U.S. 515 (1832)",
      "McClanahan v. Arizona State Tax Comm'n, 411 U.S. 164 (1973)",
      "White Mountain Apache Tribe v. Bracker, 448 U.S. 136 (1980)",
      "Indian Canons of Construction",
      "Federal Trust Responsibility",
    ],
    defaultFederalStatutes: [
      "U.S. Const. Art. VI § 2 — Supremacy Clause",
      "U.S. Const. Art. I § 8 — Indian Commerce Clause",
      "25 U.S.C. § 1321 — Retrocession of state jurisdiction",
    ],
    signatureRequirements: ["Chief Justice & Trustee"],
    buildContent(vars) {
      return [
        `JURISDICTIONAL STATEMENT`,
        `SOVEREIGN OFFICE OF THE CHIEF JUSTICE & TRUSTEE`,
        ``,
        `Re: ${vars.subject ?? "[Subject Matter / Case]"}`,
        `To: ${vars.addressee ?? "[State Agency / Court / Entity]"}`,
        ``,
        `STATEMENT OF FEDERAL AND TRIBAL JURISDICTION`,
        ``,
        `The Sovereign Office of the Chief Justice & Trustee hereby provides notice of federal and tribal jurisdiction over the above-captioned matter. This statement is issued under the authority of federal Indian law, the Federal Trust Responsibility, and the inherent sovereign authority of the tribal nation.`,
        ``,
        `I. FEDERAL SUPREMACY`,
        ``,
        `Pursuant to the Supremacy Clause of the United States Constitution (Art. VI, § 2), federal law governs all matters involving Indian tribes, Indian lands, and Indian persons. Any state or county law, ordinance, regulation, or court order that conflicts with federal Indian law is preempted and of no force or effect. McClanahan v. Arizona State Tax Comm'n, 411 U.S. 164 (1973).`,
        ``,
        `II. TRIBAL SOVEREIGN JURISDICTION`,
        ``,
        `The tribal nation exercises inherent sovereign jurisdiction over: (a) all matters affecting tribal members; (b) all activities occurring within Indian Country; (c) all matters involving Indian children under ICWA; (d) all trust land transactions; and (e) all matters within the scope of the Federal Trust Responsibility. Worcester v. Georgia, 31 U.S. 515 (1832).`,
        ``,
        `III. STATE JURISDICTION LIMITATION`,
        ``,
        `State courts and agencies lack jurisdiction over the following matters absent express Congressional authorization: (a) civil matters between Indians arising in Indian Country (Williams v. Lee, 358 U.S. 217 (1959)); (b) matters governed by ICWA (25 U.S.C. § 1911); (c) taxation of Indian income earned on the reservation (McClanahan); (d) land use within Indian Country (White Mountain Apache Tribe v. Bracker, 448 U.S. 136 (1980)).`,
        ``,
        `IV. INDIAN CANONS OF CONSTRUCTION`,
        ``,
        `Any ambiguity in law, treaty, statute, or regulation affecting Indian rights must be resolved in favor of the Indians. Montana v. Blackfeet Tribe, 471 U.S. 759 (1985). The Sovereign Office invokes the Indian Canons of Construction in the interpretation of all instruments and orders issued hereunder.`,
        ``,
        `V. REQUIRED ACTION`,
        ``,
        `${vars.requiredAction ?? "All parties receiving this Jurisdictional Statement are directed to cease and desist from any action that infringes upon tribal sovereignty or federal Indian law protections, and to comply with all instruments issued by the Sovereign Office of the Chief Justice & Trustee."}`,
        ``,
        `Issued: ${vars.issuedDate ?? new Date().toLocaleDateString()}`,
      ].join("\n");
    },
    buildSignatureBlock: sig,
  },

  {
    id: "NFR",
    name: "Notice of Federal Review",
    documentType: "nfr",
    category: "Federal Review",
    troSensitive: false,
    emergencyEligible: false,
    recorderRequired: false,
    defaultDoctrines: [
      "Indian Canons of Construction — Montana v. Blackfeet Tribe",
      "Federal Trust Responsibility",
      "Worcester v. Georgia",
      "McClanahan v. Arizona State Tax Comm'n",
    ],
    defaultFederalStatutes: [
      "U.S. Const. Art. VI § 2 — Supremacy Clause",
      "25 U.S.C. § 5108 — Indian Reorganization Act",
      "25 U.S.C. § 177 — Nonintercourse Act",
      "25 U.S.C. § 13 — Snyder Act",
    ],
    signatureRequirements: ["Chief Justice & Trustee"],
    buildContent(vars) {
      return [
        `NOTICE OF FEDERAL REVIEW`,
        `SOVEREIGN OFFICE OF THE CHIEF JUSTICE & TRUSTEE`,
        ``,
        `NFR Reference: ${vars.nfrNumber ?? "NFR-" + Date.now()}`,
        `Classification: ${vars.classification ?? "[Classification Details]"}`,
        `Date: ${vars.issuedDate ?? new Date().toLocaleDateString()}`,
        ``,
        `TO: ${vars.addressee ?? "[Respondent / Agency / Court]"}`,
        ``,
        `NOTICE IS HEREBY GIVEN that the Sovereign Office of the Chief Justice & Trustee has initiated a Notice of Federal Review regarding the following matter:`,
        ``,
        `SUBJECT: ${vars.subject ?? "[Subject Matter]"}`,
        ``,
        `VIOLATION IDENTIFIED: ${vars.violationDescription ?? "[Describe the violation or issue triggering this NFR]"}`,
        ``,
        `APPLICABLE FEDERAL LAW:`,
        `The following federal laws and doctrines apply to this matter and have been violated or are at risk of violation:`,
        `${vars.federalLaws ?? "• [List applicable federal statutes and doctrines]"}`,
        ``,
        `INDIAN CANONS OF CONSTRUCTION:`,
        `Any ambiguity in interpretation of law, regulation, or fact relevant to this matter must be resolved in favor of the Indians and their rights. Montana v. Blackfeet Tribe, 471 U.S. 759 (1985).`,
        ``,
        `REQUIRED RESPONSE:`,
        `The Sovereign Office requires a written response to this Notice within ${vars.responseDays ?? "14"} days. Failure to respond or continued violation of federal Indian law will result in escalation of this matter, including referral to the Bureau of Indian Affairs, the U.S. Department of Justice, and/or appropriate federal court.`,
        ``,
        `FEDERAL REVIEW STATUS: OPEN`,
        `Assigned Officer: ${vars.assignedOfficer ?? "[Intake Officer Name]"}`,
        ``,
        `This Notice of Federal Review constitutes due process notice of the identified federal law violation(s) and the Sovereign Office's intent to enforce federal Indian law protections.`,
        ``,
        `Issued by authority of the Sovereign Office of the Chief Justice & Trustee.`,
      ].join("\n");
    },
    buildSignatureBlock: sig,
  },

  {
    id: "EMERGENCY_WELFARE",
    name: "Emergency Welfare Declaration",
    documentType: "emergency_welfare",
    category: "Welfare",
    troSensitive: true,
    emergencyEligible: true,
    recorderRequired: false,
    defaultDoctrines: [
      "Federal Trust Responsibility",
      "Indian Canons of Construction",
      "Tribal Emergency Powers",
      "25 U.S.C. § 1922 — Emergency removal authority",
    ],
    defaultFederalStatutes: [
      "25 U.S.C. § 1922 — Emergency removal of Indian child",
      "25 U.S.C. § 13 — Snyder Act welfare authority",
      "25 U.S.C. §§ 1601–1685 — Indian Health Care Improvement Act",
      "18 U.S.C. § 2265 — Full faith and credit",
    ],
    signatureRequirements: ["Chief Justice & Trustee", "Intake Officer"],
    buildContent(vars) {
      return [
        `EMERGENCY WELFARE DECLARATION`,
        `⚑ EMERGENCY — IMMEDIATE ACTION REQUIRED`,
        ``,
        `SOVEREIGN OFFICE OF THE CHIEF JUSTICE & TRUSTEE`,
        ``,
        `Declaration No.: ${vars.declarationNumber ?? "EWD-" + Date.now()}`,
        `Date/Time: ${vars.issuedDate ?? new Date().toLocaleDateString()} / ${vars.issuedTime ?? new Date().toLocaleTimeString()}`,
        ``,
        `Subject: ${vars.subject ?? "[Tribal Member / Indian Child / Community]"}`,
        ``,
        `I. EMERGENCY DECLARATION`,
        ``,
        `The Chief Justice & Trustee of the Sovereign Office hereby declares a welfare emergency affecting ${vars.subject ?? "[subject]"}. The following emergency conditions exist:`,
        ``,
        `${vars.emergencyConditions ?? "• Imminent risk to the health, safety, or welfare of an Indian child or tribal member\n• Federal welfare protections are being denied or circumvented\n• Immediate intervention is required to prevent irreparable harm"}`,
        ``,
        `II. FEDERAL AUTHORITY`,
        ``,
        `This Emergency Declaration is issued under:`,
        `• 25 U.S.C. § 1922 — Authority for emergency removal of Indian child`,
        `• 25 U.S.C. § 13 — Snyder Act federal welfare authority`,
        `• The Federal Trust Responsibility of the United States to Indian tribes`,
        `• Inherent sovereign emergency powers of the tribal court`,
        ``,
        `III. EMERGENCY ORDERS`,
        ``,
        `Effective immediately:`,
        `1. ${vars.emergencyOrder1 ?? "Emergency welfare intervention is authorized and required."}`,
        `2. ${vars.emergencyOrder2 ?? "All state agencies must immediately provide federally mandated welfare services."}`,
        `3. ${vars.emergencyOrder3 ?? "The Sovereign Office will coordinate emergency resources and relief."}`,
        ``,
        `IV. COMPLIANCE`,
        ``,
        `All state agencies, county departments, and private parties are required to comply with this Emergency Welfare Declaration pursuant to the Federal Trust Responsibility and the Supremacy Clause of the U.S. Constitution. Non-compliance will result in referral to federal authorities and pursuit of legal remedies.`,
        ``,
        `This Declaration is effective immediately and remains in force until rescinded by the Sovereign Office.`,
        ``,
        `Issued at: ${vars.issuedAt ?? "Sovereign Office of the Chief Justice & Trustee"}`,
        `Date: ${vars.issuedDate ?? new Date().toLocaleDateString()}`,
      ].join("\n");
    },
    buildSignatureBlock: sig,
  },
];

export function getTemplate(id: string): LegacyTemplate | undefined {
  return LEGACY_TEMPLATES.find((t) => t.id === id);
}

export function listTemplates(): Array<{ id: string; name: string; documentType: string; category: string; troSensitive: boolean; emergencyEligible: boolean }> {
  return LEGACY_TEMPLATES.map(({ id, name, documentType, category, troSensitive, emergencyEligible }) => ({
    id, name, documentType, category, troSensitive, emergencyEligible,
  }));
}

export const LEGACY_TEMPLATE_MAP: Record<string, string> = {
  tro_icwa: "TRO_ICWA",
  tro_general: "TRO_GENERAL",
  icwa_notice: "ICWA_NOTICE",
  protective_order: "PROTECTIVE_ORDER",
  trust_deed: "TRUST_DEED",
  jurisdictional_statement: "JURISDICTIONAL_STATEMENT",
  nfr: "NFR",
  emergency_welfare: "EMERGENCY_WELFARE",
};
