export interface HistoricalEvent {
  year: number;
  endYear?: number;
  title: string;
  description: string;
  category: "treaty" | "removal" | "racial_classification" | "federal_law" | "census" | "territory" | "pattern";
  citation?: string;
  significance?: "critical" | "high" | "moderate";
}

export const HISTORICAL_EVENTS: HistoricalEvent[] = [

  // ── TREATIES ──────────────────────────────────────────────────────
  { year: 1763, title: "Royal Proclamation", description: "British Crown reserves lands west of Appalachians for Indian nations. First formal recognition of Indian territorial sovereignty by a colonial power.", category: "treaty", citation: "Royal Proclamation of 1763", significance: "high" },
  { year: 1785, title: "Treaty of Hopewell — Cherokee", description: "First U.S. treaty with Cherokee Nation. Established boundaries and acknowledged tribal sovereignty.", category: "treaty", citation: "Treaty of Hopewell, 1785", significance: "high" },
  { year: 1786, title: "Treaty of Hopewell — Choctaw & Chickasaw", description: "U.S. acknowledges Choctaw and Chickasaw sovereignty and territorial boundaries in the Southeast.", category: "treaty", citation: "Treaties of Hopewell, 1786", significance: "high" },
  { year: 1790, title: "Indian Non-Intercourse Act", description: "Federal law prohibiting unauthorized transfer of Indian land. Any land transfer without federal approval is void. Foundational trust protection that remains in force.", category: "treaty", citation: "25 U.S.C. § 177 (1790)", significance: "critical" },
  { year: 1814, title: "Treaty of Fort Jackson", description: "Creek Nation forced to cede 23 million acres following Battle of Horseshoe Bend. First major removal of a Southeastern nation from their lands.", category: "treaty", citation: "Treaty of Fort Jackson, 1814", significance: "critical" },
  { year: 1817, title: "Treaties with Cherokee Nation (Exchange)", description: "First treaties offering land exchange — begin the pattern of 'voluntary' removal west of the Mississippi.", category: "treaty", citation: "Cherokee Exchange Treaties, 1817–1819", significance: "high" },
  { year: 1820, title: "Treaty of Doak's Stand — Choctaw", description: "Choctaw cede 5 million acres in Mississippi, receive land in present-day Arkansas and Oklahoma.", category: "treaty", citation: "Treaty of Doak's Stand, 1820", significance: "high" },
  { year: 1826, title: "Treaty of Washington — Creek", description: "Creek Nation forced to cede remaining Georgia lands and begin removal process.", category: "treaty", citation: "Treaty of Washington, 1826", significance: "high" },
  { year: 1830, title: "Treaty of Dancing Rabbit Creek — Choctaw", description: "Choctaw Nation cedes approximately 11 million acres — the entirety of Choctaw lands in Mississippi. First treaty under the Indian Removal Act. Article 14 offered citizenship to Choctaw who stayed. Foundation of Mathias El Tribe treaty standing.", category: "treaty", citation: "Treaty of Dancing Rabbit Creek, Sep. 27, 1830 (7 Stat. 333)", significance: "critical" },
  { year: 1832, title: "Treaty of Pontotoc Creek — Chickasaw", description: "Chickasaw Nation cedes all lands east of the Mississippi. Removal to Indian Territory begins.", category: "treaty", citation: "Treaty of Pontotoc Creek, 1832", significance: "high" },
  { year: 1835, title: "Treaty of New Echota — Cherokee", description: "Fraudulent treaty signed by a small minority of Cherokee. Used to justify Cherokee removal. Supreme Court later acknowledged it was not authorized by the Nation.", category: "treaty", citation: "Treaty of New Echota, Dec. 29, 1835 (7 Stat. 478)", significance: "critical" },
  { year: 1855, title: "Choctaw-Chickasaw Treaty of 1855", description: "Reorganized governance structure of Choctaw and Chickasaw nations in Indian Territory.", category: "treaty", citation: "Choctaw-Chickasaw Treaty, 1855", significance: "moderate" },
  { year: 1866, title: "Reconstruction Treaties — Five Civilized Tribes", description: "Post-Civil War treaties forced on Southeast Indian nations. Required adoption of freed enslaved people as tribal citizens. Realigned tribal sovereignty under federal Reconstruction policy.", category: "treaty", citation: "Reconstruction Treaties, 1866", significance: "high" },
  { year: 1871, title: "End of Treaty-Making Era", description: "Congress declares no Indian nation shall be treated with by treaty. Transfers power over Indian affairs from Senate (treaty) to full Congress (legislation). Existing treaties remain in force.", category: "federal_law", citation: "Indian Appropriations Act, 1871", significance: "critical" },

  // ── REMOVAL & DISPLACEMENT ─────────────────────────────────────────
  { year: 1830, title: "Indian Removal Act Signed", description: "President Jackson signs Act authorizing forced removal of all eastern Indian nations to lands west of the Mississippi. Opens path for state seizure of Indian territory.", category: "removal", citation: "Indian Removal Act, May 28, 1830 (4 Stat. 411)", significance: "critical" },
  { year: 1831, title: "Choctaw Removal Begins", description: "First Choctaw removal parties leave Mississippi. Three waves of removal (1831, 1832, 1833). Thousands die of cholera, cold, and starvation. First 'trail of tears.'", category: "removal", citation: "Choctaw Removal, 1831–1833", significance: "critical" },
  { year: 1832, title: "Worcester v. Georgia — State Law Has No Force", description: "Supreme Court holds Georgia laws have no force in Cherokee territory. Jackson refuses to enforce decision. Establishes that states cannot extend their laws over Indian nations — a doctrine that remains controlling law.", category: "federal_law", citation: "Worcester v. Georgia, 31 U.S. 515 (1832)", significance: "critical" },
  { year: 1836, title: "Creek Removal — Second Creek War", description: "U.S. military force deployed to remove Creek Nation from Alabama. Approximately 3,500 Creek die during removal. Many removed in chains.", category: "removal", citation: "Creek Removal, 1836–1837", significance: "critical" },
  { year: 1838, title: "Trail of Tears — Cherokee Removal", description: "U.S. Army forces approximately 16,000 Cherokee west at gunpoint. Approximately 4,000 die. Among the most documented forced removals in American history.", category: "removal", citation: "Cherokee Removal (Trail of Tears), 1838–1839", significance: "critical" },
  { year: 1830, endYear: 1850, title: "Removal Era — General Pattern", description: "Systematic removal of all eastern Indian nations. Used starvation, disease, military force, fraudulent land purchases, and legal manipulation. Members who stayed behind were often reclassified, hidden, or stripped of status.", category: "removal", citation: "Indian Removal Era, 1830–1850", significance: "critical" },
  { year: 1850, endYear: 1887, title: "Reservation Policy Era", description: "Federal policy of confining Indian nations to bounded reservations. Compression of territorial sovereignty. Further displacement from traditional lands within existing territory.", category: "removal", citation: "Reservation Era, 1850–1887", significance: "high" },
  { year: 1887, title: "General Allotment Act (Dawes Act)", description: "Breaks up tribal communal land holdings into individual allotments (160 acres per family). Remaining land — over 90 million acres — opened to non-Indian settlement. Designed to destroy tribal land base and communal governance.", category: "removal", citation: "General Allotment Act, Feb. 8, 1887 (24 Stat. 388)", significance: "critical" },
  { year: 1898, title: "Curtis Act — Indian Territory Allotment", description: "Forces allotment on Five Civilized Tribes in Indian Territory (present-day Oklahoma). Dismantles tribal governments and courts. Creates Dawes Rolls as basis for land eligibility — the origin of enrollment list confusion.", category: "removal", citation: "Curtis Act, 1898", significance: "critical" },
  { year: 1907, title: "Oklahoma Statehood — Indian Territory Dissolved", description: "Indian Territory formally absorbed into State of Oklahoma. Tribal land base dramatically reduced. Many Indian people absorbed into state jurisdiction and reclassified as 'white' or 'Negro' to access services.", category: "removal", citation: "Oklahoma Enabling Act, 1906", significance: "critical" },
  { year: 1953, endYear: 1968, title: "Termination Era", description: "Congress terminates federal recognition of over 100 Indian tribes. Tribal lands transferred to state jurisdiction or sold. Federal services ended. Designed to dissolve Indian communities by administrative action.", category: "removal", citation: "House Concurrent Resolution 108, 1953", significance: "critical" },
  { year: 1956, title: "Indian Relocation Act — Urban Displacement", description: "Federal program actively moves Indian people from reservations to cities (Chicago, Los Angeles, Denver, etc.) with promises of jobs and housing. Fragments tribal communities and creates 'urban Indian' population.", category: "removal", citation: "Indian Relocation Act, 1956", significance: "high" },

  // ── RACIAL CLASSIFICATION ──────────────────────────────────────────
  { year: 1790, title: "First U.S. Census — Racial Categories Begin", description: "First federal census counts 'free white persons' and 'all other free persons.' Indian people not enumerated unless 'taxed' — i.e., assimilated. Beginning of the administrative erasure of Indian identity.", category: "census", citation: "Census Act, 1790", significance: "high" },
  { year: 1850, title: "Census — 'Indian' Category Added", description: "U.S. Census formally adds 'Indian' as a racial category — but applied inconsistently. Many Indian people counted as 'B' (Black), 'M' (Mulatto), or 'W' (White) based on enumerator perception, not self-identification.", category: "census", citation: "U.S. Census, 1850", significance: "critical" },
  { year: 1860, title: "Census — Racial Labeling of Mixed-Ancestry People", description: "Enumerators label people as 'M' (Mulatto) — covering mixed African, Indian, and European ancestry. Indian identity routinely absorbed into 'colored' or 'Mulatto' categories. Creates the basis for later misclassification.", category: "census", citation: "U.S. Census, 1860", significance: "critical" },
  { year: 1870, title: "Census — 'Indian' Count Drops After Removal", description: "Post-removal census shows sharp decline in 'Indian' enumeration in Southeast. Many Southeastern Indian people counted as 'B,' 'M,' or 'W.' First major administrative under-count of Indian people who remained.", category: "census", citation: "U.S. Census, 1870", significance: "critical" },
  { year: 1880, title: "Census — Schedule for Indians Introduced", description: "Special 'Indian Schedule' created for reservation populations only. Off-reservation Indian people continue to be classified by appearance or enumerator judgment. Further fragments the administrative record.", category: "census", citation: "U.S. Census, 1880", significance: "high" },
  { year: 1896, title: "Plessy v. Ferguson — Racial Caste Codified", description: "'Separate but equal' doctrine enforces binary racial classification (white/colored). Indian people in the South forced into 'colored' schools, facilities, and legal status. Indian identity legally erased in daily governance.", category: "racial_classification", citation: "Plessy v. Ferguson, 163 U.S. 537 (1896)", significance: "critical" },
  { year: 1900, title: "Census — Blood Quantum Questions Begin", description: "Census enumerators begin recording 'fraction of blood' — Indian, white, or Black. Blood quantum becomes an administrative tool to classify and limit Indian identity. Applied inconsistently, especially in the Southeast.", category: "census", citation: "U.S. Census, 1900", significance: "critical" },
  { year: 1907, endYear: 1914, title: "Virginia — Racial Integrity Beginning", description: "Virginia begins administrative racial registration. People of mixed ancestry pushed into binary classifications. Indian families in Virginia begin systematic pressure to identify as 'white' or 'colored' to access services.", category: "racial_classification", citation: "Virginia Racial Registration, 1907+", significance: "high" },
  { year: 1910, title: "Census — Southeast Indian Under-Count", description: "Large numbers of Southeastern Indian people — particularly in Mississippi, Alabama, Georgia — enumerated as 'B' (Black/Negro) or 'W' (White). Identity in records does not match lived identity.", category: "census", citation: "U.S. Census, 1910", significance: "critical" },
  { year: 1920, title: "Census — 'Indian' Category Further Restricted", description: "Instructions to enumerators tighten 'Indian' classification: primarily for reservation populations. Off-reservation Indian people, especially in the South, systematically undercounted.", category: "census", citation: "U.S. Census, 1920", significance: "high" },
  { year: 1924, title: "Virginia Racial Integrity Act", description: "Virginia law defines only two races: white and colored. All people of Indian ancestry classified as 'colored' unless they could prove 'pure' white heritage. Walter Plecker's Bureau of Vital Statistics systematically reclassified Indian families as 'colored.' Known as 'Paper Genocide.'", category: "racial_classification", citation: "Virginia Racial Integrity Act, 1924 (Va. Code § 5099a)", significance: "critical" },
  { year: 1924, title: "Indian Citizenship Act", description: "U.S. declares all non-citizen Indians born in the U.S. to be citizens. Does NOT extinguish tribal citizenship or sovereignty. Often misread as making Indian people 'no longer Indian.'", category: "federal_law", citation: "Indian Citizenship Act, June 2, 1924 (43 Stat. 253)", significance: "high" },
  { year: 1930, title: "Census — 'Negro' Reclassification of Indian Families", description: "In some Southern states, enumerators reclassify families previously identified as Indian to 'Negro' or 'Mulatto.' Administrative reclassification often based on neighborhood, land ownership, or local prejudice.", category: "census", citation: "U.S. Census, 1930", significance: "critical" },
  { year: 1924, endYear: 1967, title: "Plecker's Reclassification Campaign — Virginia", description: "Walter Plecker, Virginia's first registrar of vital statistics, runs a decades-long campaign to reclassify Indian families as 'colored' in all state records. Birth, death, and marriage records altered. Many Indian families moved out of state or hid their identity.", category: "racial_classification", citation: "Virginia Bureau of Vital Statistics under Walter Plecker, 1924–1946", significance: "critical" },
  { year: 1940, title: "Census — Indian Identity Suppression Continues", description: "Southeastern Indian people continue to be disproportionately enumerated as non-Indian in federal census records. Record gap between self-identified Indian population and census count.", category: "census", citation: "U.S. Census, 1940", significance: "high" },
  { year: 1950, title: "Census — Binary Race Categories Persist", description: "Census racial categories still do not adequately capture Indian identity outside of reservation contexts. Continued systematic undercounting of Southeastern Indian communities.", category: "census", citation: "U.S. Census, 1950", significance: "moderate" },

  // ── FEDERAL INDIAN LAW ─────────────────────────────────────────────
  { year: 1824, title: "Bureau of Indian Affairs Created", description: "Office of Indian Affairs established under War Department. Begins the administrative apparatus that will later be used to manage — and restrict — Indian identity and land.", category: "federal_law", citation: "BIA established, 1824", significance: "moderate" },
  { year: 1831, title: "Cherokee Nation v. Georgia", description: "Supreme Court holds Cherokee Nation is a 'domestic dependent nation' — neither foreign nation nor U.S. state. Creates the framework of the federal-tribal trust relationship.", category: "federal_law", citation: "Cherokee Nation v. Georgia, 30 U.S. 1 (1831)", significance: "critical" },
  { year: 1883, title: "Ex Parte Crow Dog — Inherent Criminal Jurisdiction", description: "Supreme Court recognizes tribes' inherent jurisdiction over their own members in criminal matters. Foundational case for tribal self-governance authority.", category: "federal_law", citation: "Ex Parte Crow Dog, 109 U.S. 556 (1883)", significance: "high" },
  { year: 1884, title: "Elk v. Wilkins — Indian Citizenship Denied", description: "Supreme Court holds that an Indian who has separated from his tribe and adopted 'habits of civilization' is still not a U.S. citizen without an act of Congress. Creates the 'detribalization' framework.", category: "federal_law", citation: "Elk v. Wilkins, 112 U.S. 94 (1884)", significance: "high" },
  { year: 1903, title: "Lone Wolf v. Hitchcock — Congress Has Plenary Power", description: "Supreme Court holds Congress has 'plenary power' over Indian affairs and can abrogate treaties unilaterally. Removes judicial check on Congress's power to terminate tribal rights.", category: "federal_law", citation: "Lone Wolf v. Hitchcock, 187 U.S. 553 (1903)", significance: "critical" },
  { year: 1934, title: "Indian Reorganization Act (Wheeler-Howard Act)", description: "Ends allotment, restores some tribal lands, encourages tribal self-governance through constitutions. Partial reversal of Dawes Act policies. Many tribes adopt IRA constitutions — some creating enrollment criteria that later cause confusion.", category: "federal_law", citation: "Indian Reorganization Act, June 18, 1934 (48 Stat. 984)", significance: "critical" },
  { year: 1953, title: "Public Law 280 — State Criminal Jurisdiction", description: "Gives certain states (California, Minnesota, Nebraska, Oregon, Wisconsin) criminal and some civil jurisdiction over Indian reservations. Directly undermines tribal jurisdiction in those states.", category: "federal_law", citation: "Public Law 280, Aug. 15, 1953 (67 Stat. 588)", significance: "high" },
  { year: 1968, title: "Indian Civil Rights Act", description: "Applies most (not all) Bill of Rights protections to tribal members in relation to their own tribal governments. Provides due process and equal protection standards within tribal governance.", category: "federal_law", citation: "Indian Civil Rights Act, 1968 (25 U.S.C. §§ 1301–1304)", significance: "high" },
  { year: 1975, title: "Indian Self-Determination and Education Assistance Act", description: "Landmark act ending termination era. Tribes can contract to run their own federal programs. Broad 'Indian' definition in 25 U.S.C. § 5304 — not tied to BIA administrative lists.", category: "federal_law", citation: "ISDEAA, Jan. 4, 1975 (25 U.S.C. §§ 5301 et seq.)", significance: "critical" },
  { year: 1975, title: "Passamaquoddy Tribe v. Morton", description: "First Circuit holds the Non-Intercourse Act (1790) applies to tribes not federally recognized. Trust responsibility does NOT require administrative list placement. Foundational case against 'you're not on our list' arguments.", category: "federal_law", citation: "Passamaquoddy Tribe v. Morton, 528 F.2d 370 (1st Cir. 1975)", significance: "critical" },
  { year: 1978, title: "Indian Child Welfare Act (ICWA)", description: "Federal law establishing tribal jurisdiction over child custody proceedings involving Indian children. Protects family continuity and cultural identity. Acknowledges forced assimilation through child removal as historical harm.", category: "federal_law", citation: "ICWA, Nov. 8, 1978 (25 U.S.C. §§ 1901–1963)", significance: "critical" },
  { year: 1978, title: "American Indian Religious Freedom Act", description: "Federal policy protects the religious rights, places of worship, and sacred objects of Indian people. Acknowledges historic suppression of Native religious practices.", category: "federal_law", citation: "AIRFA, Aug. 11, 1978 (42 U.S.C. § 1996)", significance: "high" },
  { year: 1988, title: "Indian Gaming Regulatory Act", description: "Establishes federal framework for tribal gaming operations. Significant in tribal economic development and the reassertion of tribal territorial sovereignty.", category: "federal_law", citation: "IGRA, Oct. 17, 1988 (25 U.S.C. §§ 2701 et seq.)", significance: "moderate" },
  { year: 1990, title: "Native American Languages Act", description: "Federal policy affirming the right of Indian people to use, practice, and develop Native American languages. Acknowledges historic suppression of Native languages.", category: "federal_law", citation: "Native American Languages Act, 1990 (25 U.S.C. §§ 2901 et seq.)", significance: "high" },
  { year: 1990, title: "NAGPRA — Repatriation Rights", description: "Native American Graves Protection and Repatriation Act. Federal agencies and museums must return ancestral remains and sacred objects to lineal descendants and tribal nations.", category: "federal_law", citation: "NAGPRA, Nov. 16, 1990 (25 U.S.C. §§ 3001–3013)", significance: "high" },
  { year: 1994, title: "Violence Against Women Act — Tribal Provisions", description: "VAWA includes tribal provisions recognizing tribal court authority over domestic violence cases. Affirms interjurisdictional enforcement of tribal protective orders.", category: "federal_law", citation: "VAWA, 1994 (amended 2013)", significance: "high" },
  { year: 2024, title: "Loper Bright — Chevron Deference Overturned", description: "Supreme Court overturns Chevron doctrine. Federal agencies may no longer rely solely on their own interpretation of ambiguous statutes. Agency administrative convenience arguments that narrow Indian rights are now legally vulnerable. Post-Loper Bright, classification challenges are stronger.", category: "federal_law", citation: "Loper Bright Enterprises v. Raimondo, 603 U.S. ___ (2024)", significance: "critical" },

  // ── TERRITORY & LOCAL ──────────────────────────────────────────────
  { year: 1830, endYear: 1860, title: "Mississippi — Indian Land Open to Settlement", description: "Following Removal Act, Mississippi opens former Choctaw and Chickasaw lands to non-Indian settlement. Indian people who remained faced escalating violence, dispossession, and legal erasure.", category: "territory", citation: "Mississippi land records, 1830–1860", significance: "high" },
  { year: 1861, endYear: 1865, title: "Civil War — Indian Territory Divided", description: "Five Civilized Tribes divided between Union and Confederate alliances. Indian Territory becomes active war zone. Many Indian people killed, communities destroyed, government institutions disrupted.", category: "territory", citation: "Civil War in Indian Territory, 1861–1865", significance: "high" },
  { year: 1889, title: "Oklahoma Land Runs — 'Unassigned' Indian Land Opened", description: "U.S. opens Indian Territory lands to non-Indian settlement by land run. 2 million acres claimed in one day. Beginning of the final erosion of Indian territorial integrity in Oklahoma.", category: "territory", citation: "Oklahoma Land Run, Apr. 22, 1889", significance: "critical" },
  { year: 1898, endYear: 1907, title: "Dawes Rolls — Indian Territory Enrollment", description: "Commission to the Five Civilized Tribes creates enrollment rolls for allotment. Incomplete, politically manipulated, and racially filtered. Exclusion from the Dawes Rolls has been misread as proof of non-Indian status — it is not.", category: "territory", citation: "Dawes Commission Rolls, 1898–1914", significance: "critical" },

  // ── PATTERN MARKERS ───────────────────────────────────────────────
  { year: 1830, endYear: 2024, title: "Pattern: Identity Interruption Is Not Extinction", description: "Displacement, racial reclassification, name changes, census misclassification, administrative exclusion — these are evidence of interruption, not absence. The system should not treat identity loss in records as proof of nonexistence. Each gap in the record is itself evidence of a harm that occurred.", category: "pattern", citation: "Foundational interpretive principle — Mathias El Tribe Office of the Chief Justice", significance: "critical" },
  { year: 1850, endYear: 1970, title: "Pattern: Misclassification as Administrative Harm", description: "Systematic misclassification of Indian people as 'colored,' 'mulatto,' 'negro,' or 'white' in census and vital records was not error — it was policy. It was used to deny land claims, tribal membership, federal services, and legal standing. Each misclassification is a documented harm, not a settled fact.", category: "pattern", citation: "Pattern Recognition — Racial Relabeling as Administrative Violence", significance: "critical" },
  { year: 1887, endYear: 1934, title: "Pattern: Land Loss Through Allotment", description: "Indian land ownership dropped from approximately 138 million acres (1887) to 48 million acres (1934) — a loss of 65% in 47 years. Allotment was the primary mechanism. Individual allotments were sold, taxed, or taken through probate manipulation.", category: "pattern", citation: "Allotment era statistics, 1887–1934", significance: "critical" },
  { year: 1924, endYear: 1967, title: "Pattern: Name Changes as Survival Strategy", description: "Indian families frequently changed surnames, moved to new counties or states, or adopted different racial identities as survival strategies during periods of extreme racial violence and dispossession. A changed name in the record is not proof of a different identity.", category: "pattern", citation: "Pattern Recognition — Identity Concealment as Survival", significance: "critical" },
];

export function getHistoricalEventsForAncestor(birthYear: number | null, deathYear: number | null): HistoricalEvent[] {
  if (!birthYear && !deathYear) return HISTORICAL_EVENTS;
  const birth = birthYear ?? 1700;
  const death = deathYear ?? new Date().getFullYear();
  return HISTORICAL_EVENTS.filter(e => {
    const eStart = e.year;
    const eEnd = e.endYear ?? e.year;
    return eStart <= death + 10 && eEnd >= birth - 10;
  });
}
