import { Router, type IRouter } from "express";
import healthRouter from "./health";
import trustTemplatesRouter from "./trust/templates";
import trustInstrumentsRouter from "./trust/instruments";
import trustFilingsRouter from "./trust/filings";
import classifyRouter from "./tribal/classify";
import nfrRouter from "./court/nfr";
import complaintsRouter from "./complaints/index";
import calendarRouter from "./calendar/index";
import tasksRouter from "./tasks/index";
import searchRouter from "./search/index";
import userProfileRouter from "./user/profile";
import adminEntraRouter from "./admin/entra";
import adminBootstrapRouter from "./admin/bootstrap";
import welfareRouter from "./court/welfare";
import notificationsRouter from "./notifications";
import lawRouter from "./law";
import courtDocumentsRouter from "./court/documents";
import intakeAiRouter from "./intake/ai";
import familyTreeRouter from "./family-tree";
import membershipRouter from "./membership";
import medicalNotesRouter from "./medical/notes";
import orgRouter from "./org/overview";
import chatRouter from "./chat/index";
import identityGatewayRouter from "./identity/gateway";
import identityTribalIdRouter from "./identity/tribal-id";
import draftsRouter from "./drafts/index";
import documentsRouter from "./documents/index";
import authMicrosoftRouter from "./auth/microsoft";
import authPasswordRouter from "./auth/password";
import authSessionRouter from "./auth/session";
import m365FactsRouter from "./m365/facts";
import m365WebhookRouter from "./m365/webhook";
import m365StatusRouter from "./m365/status";
import lineageImportRouter from "./lineage/import";
import lineageNodesRouter from "./lineage/nodes";
import delegationsRouter from "./delegations/index";
import communityDirectoryRouter from "./community/directory";
import communityLawRouter from "./community/law";
import communityForumRouter from "./community/forum";
import communityAiRouter from "./community/ai-guidance";
import communityActivityRouter from "./community/activity";
import businessAnalyzeRouter from "./business/analyze";
import businessConceptsRouter from "./business/concepts";

const router: IRouter = Router();

router.use(healthRouter);

router.use("/trust/templates", trustTemplatesRouter);
router.use("/trust/instruments", trustInstrumentsRouter);
router.use("/trust/filings", trustFilingsRouter);
router.use("/tribal/classify", classifyRouter);
router.use("/court/nfr", nfrRouter);
router.use("/court/documents", courtDocumentsRouter);
router.use("/court/welfare", welfareRouter);
router.use("/complaints", complaintsRouter);
router.use("/calendar", calendarRouter);
router.use("/tasks", tasksRouter);
router.use("/search", searchRouter);
router.use("/user/profile", userProfileRouter);
router.use("/admin/entra", adminEntraRouter);
router.use("/admin/bootstrap", adminBootstrapRouter);
router.use("/notifications", notificationsRouter);
router.use("/law", lawRouter);
router.use("/intake/ai", intakeAiRouter);
router.use("/family-tree", familyTreeRouter);
router.use("/membership", membershipRouter);
router.use("/medical/notes", medicalNotesRouter);
router.use("/org", orgRouter);
router.use("/chat", chatRouter);
router.use("/identity", identityGatewayRouter);
router.use("/identity", identityTribalIdRouter);
router.use("/drafts", draftsRouter);
router.use("/documents", documentsRouter);
router.use("/auth/microsoft", authMicrosoftRouter);
router.use("/auth", authPasswordRouter);
router.use("/auth", authSessionRouter);
router.use("/facts", m365FactsRouter);
router.use("/m365", m365WebhookRouter);
router.use("/m365", m365StatusRouter);
router.use("/lineage/import", lineageImportRouter);
router.use("/lineage/nodes", lineageNodesRouter);
router.use("/delegations", delegationsRouter);
router.use("/community/directory", communityDirectoryRouter);
router.use("/community/law", communityLawRouter);
router.use("/community/forum", communityForumRouter);
router.use("/community/ai", communityAiRouter);
router.use("/community/activity", communityActivityRouter);
router.use("/business/analyze", businessAnalyzeRouter);
router.use("/business/concepts", businessConceptsRouter);

export default router;
