CREATE TABLE "atlas_events" (
  "id" serial PRIMARY KEY NOT NULL,
  "event_id" text NOT NULL,
  "title" text NOT NULL,
  "short_title" text,
  "year" integer NOT NULL,
  "date_start" text,
  "date_end" text,
  "era" text NOT NULL,
  "event_type" text NOT NULL,
  "policy_area" text NOT NULL,
  "description" text NOT NULL,
  "plain_language_summary" text NOT NULL,
  "severity_level" text DEFAULT 'moderate' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "identity_impact" text,
  "reclassification_impact" text,
  "continuity_impact" text,
  "continuity_survival_note" text,
  "family_impact" text,
  "urbanization_impact" text,
  "health_access_impact" text,
  "public_school_impact" text,
  "land_impact" text,
  "jurisdiction_impact" text,
  "housing_impact" text,
  "labor_migration_impact" text,
  "modern_effect" text,
  "ancestor_relevance_note" text,
  "affected_people" text,
  "affected_regions" text[] DEFAULT '{}' NOT NULL,
  "states_affected" text[] DEFAULT '{}' NOT NULL,
  "coordinate_lat" double precision,
  "coordinate_lng" double precision,
  "source_title" text DEFAULT '' NOT NULL,
  "source_url" text DEFAULT '' NOT NULL,
  "source_type" text,
  "citation" text,
  "public_law_number" text,
  "tags" text[] DEFAULT '{}' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "atlas_events_event_id_unique" UNIQUE("event_id")
);
